export const LANGUAGES = [
    { code: 'af', name: 'Afrikaans', emoji: '🇿🇦', locale: 'af-ZA' },
    { code: 'ar', name: 'Arabic', emoji: '🇸🇦', locale: 'ar-SA' },
    { code: 'be', name: 'Belarusian', emoji: '🇧🇾', locale: 'be-BY' },
    { code: 'bn', name: 'Bengali', emoji: '🇧🇩', locale: 'bn-BD' },
    { code: 'bg', name: 'Bulgarian', emoji: '🇧🇬', locale: 'bg-BG' },
    { code: 'ca', name: 'Catalan', emoji: '🇪🇸', locale: 'ca-ES' },
    { code: 'zh', name: 'Chinese (Simplified)', emoji: '🇨🇳', locale: 'zh-CN' },
    { code: 'zh-tw', name: 'Chinese (Traditional)', emoji: '🇹🇼', locale: 'zh-TW' },
    { code: 'hr', name: 'Croatian', emoji: '🇭🇷', locale: 'hr-HR' },
    { code: 'cs', name: 'Czech', emoji: '🇨🇿', locale: 'cs-CZ' },
    { code: 'da', name: 'Danish', emoji: '🇩🇰', locale: 'da-DK' },
    { code: 'nl', name: 'Dutch', emoji: '🇳🇱', locale: 'nl-NL' },
    { code: 'en', name: 'English', emoji: '🇺🇸', locale: 'en-US' },
    { code: 'et', name: 'Estonian', emoji: '🇪🇪', locale: 'et-EE' },
    { code: 'fi', name: 'Finnish', emoji: '🇫🇮', locale: 'fi-FI' },
    { code: 'fr', name: 'French', emoji: '🇫🇷', locale: 'fr-FR' },
    { code: 'de', name: 'German', emoji: '🇩🇪', locale: 'de-DE' },
    { code: 'el', name: 'Greek', emoji: '🇬🇷', locale: 'el-GR' },
    { code: 'he', name: 'Hebrew', emoji: '🇮🇱', locale: 'he-IL' },
    { code: 'hi', name: 'Hindi', emoji: '🇮🇳', locale: 'hi-IN' },
    { code: 'as', name: 'Assamese', emoji: '🇮🇳', locale: 'as-IN' },
    { code: 'bn-IN', name: 'Bengali', emoji: '🇮🇳', locale: 'bn-IN' },
    { code: 'gu', name: 'Gujarati', emoji: '🇮🇳', locale: 'gu-IN' },
    { code: 'kn', name: 'Kannada', emoji: '🇮🇳', locale: 'kn-IN' },
    { code: 'ks', name: 'Kashmiri', emoji: '🇮🇳', locale: 'ks-IN' },
    { code: 'ml', name: 'Malayalam', emoji: '🇮🇳', locale: 'ml-IN' },
    { code: 'mr', name: 'Marathi', emoji: '🇮🇳', locale: 'mr-IN' },
    { code: 'ne', name: 'Nepali', emoji: '🇳🇵', locale: 'ne-NP' },
    { code: 'or', name: 'Oriya', emoji: '🇮🇳', locale: 'or-IN' },
    { code: 'pa', name: 'Punjabi', emoji: '🇮🇳', locale: 'pa-IN' },
    { code: 'sa', name: 'Sanskrit', emoji: '🇮🇳', locale: 'sa-IN' },
    { code: 'ta', name: 'Tamil', emoji: '🇮🇳', locale: 'ta-IN' },
    { code: 'te', name: 'Telugu', emoji: '🇮🇳', locale: 'te-IN' },
    { code: 'ur', name: 'Urdu', emoji: '🇵🇰', locale: 'ur-PK' },
    { code: 'hu', name: 'Hungarian', emoji: '🇭🇺', locale: 'hu-HU' },
    { code: 'id', name: 'Indonesian', emoji: '🇮🇩', locale: 'id-ID' },
    { code: 'it', name: 'Italian', emoji: '🇮🇹', locale: 'it-IT' },
    { code: 'ja', name: 'Japanese', emoji: '🇯🇵', locale: 'ja-JP' },
    { code: 'ko', name: 'Korean', emoji: '🇰🇷', locale: 'ko-KR' },
    { code: 'lv', name: 'Latvian', emoji: '🇱🇻', locale: 'lv-LV' },
    { code: 'lt', name: 'Lithuanian', emoji: '🇱🇹', locale: 'lt-LT' },
    { code: 'ms', name: 'Malay', emoji: '🇲🇾', locale: 'ms-MY' },
    { code: 'nb', name: 'Norwegian', emoji: '🇳🇴', locale: 'nb-NO' },
    { code: 'fa', name: 'Persian', emoji: '🇮🇷', locale: 'fa-IR' },
    { code: 'pl', name: 'Polish', emoji: '🇵🇱', locale: 'pl-PL' },
    { code: 'pt', name: 'Portuguese', emoji: '🇵🇹', locale: 'pt-PT' },
    { code: 'ro', name: 'Romanian', emoji: '🇷🇴', locale: 'ro-RO' },
    { code: 'ru', name: 'Russian', emoji: '🇷🇺', locale: 'ru-RU' },
    { code: 'sr', name: 'Serbian', emoji: '🇷🇸', locale: 'sr-RS' },
    { code: 'sk', name: 'Slovak', emoji: '🇸🇰', locale: 'sk-SK' },
    { code: 'sl', name: 'Slovenian', emoji: '🇸🇮', locale: 'sl-SI' },
    { code: 'es', name: 'Spanish', emoji: '🇪🇸', locale: 'es-ES' },
    { code: 'sv', name: 'Swedish', emoji: '🇸🇪', locale: 'sv-SE' },
    { code: 'th', name: 'Thai', emoji: '🇹🇭', locale: 'th-TH' },
    { code: 'tr', name: 'Turkish', emoji: '🇹🇷', locale: 'tr-TR' },
    { code: 'uk', name: 'Ukrainian', emoji: '🇺🇦', locale: 'uk-UA' },
    { code: 'vi', name: 'Vietnamese', emoji: '🇻🇳', locale: 'vi-VN' }
] as const;

export type Language = (typeof LANGUAGES)[number];
